version: '3.8'

services: # app components like ui , logs , db 

  saritha-ui-service:

    image: saritha-webui:version$BUILD_NUMBER 

    build:

      context: . # location of dockerfile 

      dockerfile: Dockerfile  # name of Dockerfile 

    container_name: saritha-web-c1 # name of container 

    ports:

      - 1254:80 # you can use 1024-5000 range